schema_version = "1.0.0"
id = "gamiflow"
name = "GamiFlow"
version = "1.2.3"
tagline = "Easier game asset creation"
maintainer = "Mathieu Einig"
type = "add-on"
website = "https://github.com/matheinig/GamiFlow"
tags = ["Import-Export", "Object"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
[permissions]
files = "Export FBX files to disk"

